<?php require_once "Template/header.phtml" ?>
        <div class="row justify-content-center align-items-center ">
             <div>
                <h5>The Admin Dashbord</h5>
             </div>
        </div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="adminDashboard.php?tab=checkSignup">Check Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="adminDashboard.php?tab=manageTeams">Manage teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="adminDashboard.php?tab=manageUsers">Manage users</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php switch ($page) {
                case "AddTeam":
                    require_once "Template/manageTeams.phtml";
                    break;
                case "checkSignup":
                    require_once "Template/checkSignup.phtml";
                    break;
                case "manageUsers":
                    require_once "Template/manageUsers.phtml";
                    break;
            }
            ?>
        </div>
    </div>


    <?php require_once "Template/footer.phtml"?>

