<?php require_once "Template/header.phtml" ?>
    </div>
        <h5>The Admin Dashbord</h5>
    </div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="navigation">
                <a href="adminDashboard.php?tab=addRole">Add Role</a>
                <a href="adminDashboard.php?tab=NewUser">New User</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php switch ($page) {
                case "AddRole":
                    require_once "Template/addRole.phtml";
                    break;
                case "NewUser":
                    require_once "Template/newUser.phtml";
                    break;
            } ?>
        </div>
    </div>

<?php require_once "Template/footer.phtml" ?>


