<?php require_once "Template/header.phtml" ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="navigation">
                <a href="adminDashboard.php?tab=addRole">Add Role</a>
                <a href="adminDashboard.php?tab=addUser">Add User</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php switch ($page) {
                case "addRole":
                    require_once "Template/addRole.phtml";
                    break;
            } ?>
        </div>
    </div>
</div>
    <h5>Index Page View</h5>

</div>
<?php require_once "Template/footer.phtml" ?>