<?php require_once "Template/header.phtml" ?>

<div class="container">
    <div class="row mt-2 text-center">
        <div class="col-md-12">
            <h4 class="display-3 text-danger">Error</h4>
            <h4 class="display-5 text-danger mb-5">You do not have authorisation to view this page</h4>
            <iframe style="width: 80%; height: 500px; margin: auto;" src="https://www.youtube.com/embed/dI0XWAMQgxc?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

        </div>
    </div>
</div>

<?php require_once "Template/footer.phtml" ?>
