<?php require_once "template/header.phtml"?>

<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6">

            <?php foreach ($errors as $msg) : ?>
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <?= $msg ?>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <?php endforeach; ?>

            <form action="<?= $_SERVER["PHP_SELF"] ?>" method="post">
                <div class="form-group row">
                    <h2>Login:</h2>
                </div>

                <div class="form-group row">
                    <label for="username">Username:</label>
                    <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
                </div>

                <div class="form-group row">
                    <label for="password">Password:</label>
                    <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                <div class="form-group row">
                    <button class="btn btn-success" type="submit" name="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>


<?php require_once "template/footer.phtml"?>