<?php require_once "template/header.phtml"?>

<?php if (isset($message)) : ?>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <?= $message ?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php endif; ?>

<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6">
            <form>
                <h2>Sign Up:</h2>
                <div class="form-group row">
                    <label for="username">Username:</label>
                    <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
                </div>

                <div class="form-group row">
                    <label for="password">Password:</label>
                    <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                <div class="form-group row">
                    <button class="btn btn-success" type="submit" name="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>


<?php require_once "template/footer.phtml"?>
