<?php require_once "Views/Template/header.phtml"; ?>

<div class="container button-group"> <!-- all 4 options as a group, Building, Infrastructure, Demographic, Utilities. -->
    <div class="row">
        <h2>Buildings</h2>
        <div class="col-sm-12 d-flex flex-row justify-content-center align-items-center">
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showBuildingData">Show Building Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showBuildingById">Show Building Data by ID</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="createBuilding">Create New Building</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="deleteBuilding">Delete Building Data</button>
        </div>
    </div>
    <div class="row">
        <h2>Infrastructure</h2>
        <div class="col-sm-12 d-flex flex-row justify-content-center align-items-center">
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showInfrastructureData">Show Infrastructure Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showInfrastructureById">Show Infrastructure Data by ID</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="createInfrastructure">Create New Infrastructure</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="deleteInfrastructure">Delete Infrastructure</button>
        </div>
    </div>
    <div class="row">
        <h2>Demographics</h2>
        <div class="col-sm-12 d-flex flex-row justify-content-center align-items-center">
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showDemographicsData">Show Demographic Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showDemographicsById">Show Demographic Data by ID</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="createDemographics">Add New Demographic</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="deleteDemographics">Delete Demographic</button>
        </div>
    </div>
    <div class="row">
        <h2>Utilities</h2>
        <div class="col-sm-12 d-flex flex-row justify-content-center align-items-center">
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showUtilitiesData">Show Utilities Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="showUtilitiesById">Show Utilities Data by ID</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="createUtilities">Add New Utilities</button>
            <button class="button1" type="button" style="font: bold 22px Arial;" id="deleteUtilities">Delete Utilities</button>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <pre id="output" class="d-flex justify-content-center">
            </pre>
        </div>
    </div>

</div>

<?php require_once "Views/Template/footer.phtml"; ?>

<script>
    async function outputResponse(url)
    {
        document.getElementById("output").innerHTML = "<div class=\"spinner-border text-success\" style=\"width: 4em; height: 4em;\" role=\"status\">\n" +
            "                    <span class=\"sr-only\">Loading...</span>\n" +
            "                </div>";

        let promise = await fetch(url);
        let response = await promise.json();
        document.getElementById("output").innerHTML = JSON.stringify(response, undefined, 1);
    }
    
    // Show building data
    document.getElementById("showBuildingData").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showBuildingData.php");
    });

    // Show building by id
    document.getElementById("showBuildingById").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showBuildingById.php");
    });

    // Show building by id
    document.getElementById("createBuilding").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/createBuilding.php");
    });

    // Show building by id
    document.getElementById("deleteBuilding").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/deleteBuilding.php");
    });

    // Show utility data
    document.getElementById("showUtilitiesData").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showUtilitiesData.php");
    });

    // Show utility data by id
    document.getElementById("showUtilitiesById").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showUtilitiesById.php");
    });

    // Show create new utility
    document.getElementById("createUtilities").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/createUtilities.php");
    });

    // Show create new utility
    document.getElementById("deleteUtilities").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/deleteUtilities.php");
    });

    // Show Infrastructure data
    document.getElementById("showInfrastructureData").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showInfrastructureData.php");
    });

    // Show Infrastructure data
    document.getElementById("showInfrastructureById").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showInfrastructureById.php");
    });

    // Show Infrastructure data
    document.getElementById("createInfrastructure").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/createInfrastructure.php");
    });

    // Show Infrastructure data
    document.getElementById("deleteInfrastructure").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/deleteInfrastructure.php");
    });

    // Show demographic data
    document.getElementById("showDemographicsData").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showDemographicsData.php");
    });

    // Show demographic data
    document.getElementById("showDemographicsById").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/showDemographicsById.php");
    });

    // Show demographic data
    document.getElementById("createDemographics").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/createDemographics.php");
    });

    // Show demographic data
    document.getElementById("deleteDemographics").addEventListener("click", async () => {
        await outputResponse("requests/api_tests/deleteDemographics.php");
    });

</script>












