<?php require_once "Views/Template/header.phtml";

?>

<div class="container">
    <div class="row">
        <div class="col-sm-12 d-flex flex-row justify-content-center">
            <button class="button1" type="button" style="font: bold 22px Arial;">Show Building Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;">Show Infrastructure Data</button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 d-flex flex-row justify-content-center">
            <button class="button1" type="button" style="font: bold 22px Arial;">Show Demographic Data</button>
            <button class="button1" type="button" style="font: bold 22px Arial;">Show Utilities Data</button>
        </div>
    </div>

</div>

<?php

require_once "Views/Template/footer.phtml"; ?>













</body>