

<select>
    <?php
    $users = User::getAllusers();

    while($users) {
        $value.='<option value="'.$users['username'].'">';
    }
    ?>


    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
</select>

<select>
    <option value="Role 1">Role 1</option>
    <option value="Role 2">Role 2</option>
    <option value="Role 3">Role 3</option>
    <option value="Role 4">Role 4</option>
</select>

<input type="submit">

<!-- on submit insert role value into user through the db -->

