

<select>
    <?php
    $users = User::getAllusers();
    ?>

    <?php foreach($users as $user) : ?>
        <option value="<?= $user->username() ?>"><?= $user->username() ?></option>
    <?php endforeach; ?>
</select>

<select>
    <?php
    $role = Role::allRoles();
    ?>

    <?php foreach ($role as $roles) : ?>
        <option value="<?= $roles->role_name() ?>"><?= $roles->role_name() ?></option>
    <?php endforeach; ?>
</select>

<input type="submit">

<!-- on submit insert role value into user through the db -->

