<h5>Approve Signup Requests</h5>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Timestamp</th>
            <th scope="col">Accept</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (User::getAllAdminRequests() as $index => $requestUser) : ?>
            <tr id="req-<?= $requestUser->id() ?>">
                <th scope="row"><?= $index+1 ?></th>
                <td><?= $requestUser->username() ?></td>
                <td><?= date("jS \of M o H:i", strtotime($requestUser->timestamp)) ?></td>
                <td>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-success btn-sm" id="app-<?= $requestUser->id() ?>">Approve</button>
                        <button type="button" class="btn btn-danger btn-sm" id="den-<?= $requestUser->id() ?>">Deny</button>
                    </div>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
