<h5>Approve Signup Requests</h5>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Timestamp</th>
            <th scope="col">Accept</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (User::getAllAdminRequests() as $index => $requestUser) : ?>
            <tr id="req-<?= $requestUser->id() ?>">
                <th scope="row"><?= $index+1 ?></th>
                <td><?= $requestUser->username() ?></td>
                <td><?= $requestUser->email ?></td>
                <td><?= date("jS \of M o H:i", strtotime($requestUser->timestamp)) ?></td>
                <td>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-success btn-sm role-buttons" id="app-<?= $requestUser->id() ?>">Approve</button>
                        <button type="button" class="btn btn-danger btn-sm role-buttons" id="den-<?= $requestUser->id() ?>">Deny</button>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    let buttons = document.getElementsByClassName("role-buttons");
    for (let button of buttons) {
        button.addEventListener("click", function() {
            let change = this.id.split("-")[0] === "app";
            let id = this.id.substr(4);
            let body = {
                "acceptance": change,
                "id": id
            };
            fetch("requests/users/adminReq.php", {
               method: "POST",
               headers: {
                   "Content-Type": "application/json"
               },
                body: JSON.stringify(body)
            }).then(async res => {
                let json = await res.json();
                document.getElementById("req-" + id).remove();
            }).catch(function(err) {
                console.log(err);
            });
        });
    }

    function displayMessage(message)
    {
        console.log(message);
    }
</script>