<h5>Create New Role</h5>

<form method="post" action="<?= $_SERVER["PHP_SELF"] ?>?tab=<?= $page ?>">
    <div class="form-row my-3">
        <label for="group_name" class="col-form-label col-md-3">Role Name:</label>
        <div class="col-md-9">
            <input type="text" id="role_name" class="form-control" name="role_name" placeholder="Enter a role name">
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" name="createRole">Create Role</button>
    </div>
</form>

<h5>Current Roles</h5>

<?php foreach (Role::allRoles() as $role) : ?>
    <div class="group">
        <p><?= $role->role_name ?></p>
        <?php if ($role->editable) : ?>
            <form class="ml-auto" action="<?php $_SERVER["PHP_SELF"] ?>" method="post">
                <input type="hidden" name="roleID" value="<?= $role->id ?>">
                <button class="btn btn-danger btn-sm" name="deleteRole">Delete</button>
            </form>
        <?php else : ?>
            <span class="ml-auto"><i class="fas fa-lock"></i></span>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<h5>Role Permissions</h5>

<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Role</th>
            <th scope="col">Get</th>
            <th scope="col">Edit</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (Role::allRoles() as $index => $role) : ?>
            <tr>
                <th scope="row"><?= $index+1 ?></th>
                <td><?= $role->role_name ?></td>
                <td>
                    <?php if ($role->role_name == "Admin") : ?>
                        <i class="fas fa-lock text-danger"></i>
                    <?php elseif ($role->role_name == "Default") : ?>
                        <i class="fas fa-lock-open text-danger"></i>
                    <?php else : ?>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="get-perm-<?= $role->id ?>" <?= $role->hasPermission("get") ? "checked" : "" ?>>
                            <label for="get-perm-<?= $role->id ?>" class="custom-control-label"></label>
                        </div>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($role->role_name == "Admin") : ?>
                        <i class="fas fa-lock text-danger"></i>
                    <?php elseif ($role->role_name == "Default") : ?>
                        <i class="fas fa-lock text-danger"></i>
                    <?php else : ?>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="edit-perm-<?= $role->id ?>" <?= $role->hasPermission("edit") ? "checked" : "" ?>>
                        <label for="edit-perm-<?= $role->id ?>" class="custom-control-label"></label>
                    </div>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<style>
    .custom-control-label {
        cursor: pointer;
    }
</style>

<script>
    let checkboxes = document.getElementsByClassName("custom-control-input");
    for (let checkbox of checkboxes) {
        checkbox.addEventListener("change", function() {
            let id = this.id.split("-")[2];
            let permission = this.id.split("-")[0];
            let change = this.checked;

            let data = {
              "id": id,
              "permission": permission,
              "change": change
            };

            fetch("requests/users/role.php", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(data)
            }).then(async res => {
                let json = await res.json();
                console.log(json);
            }).catch(err => {
                console.log(err);
            });
        });
    }
</script>
