<h5>Create new user</h5>
<form action="<?= $_SERVER["PHP_SELF"] ?>?tab=<?= $page ?>" method="post">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
    </div>
    <div class="form-group">
        <label for="confirm_password">Confirm Password:</label>
        <input type="password" id="confirm_password" class="form-control" name="confirm_password" placeholder="Confirm password">
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" name="addUser">Create User</button>
    </div>
</form>
<!-- on submit insert role value into user through the db -->

<h5>Current Users</h5>
<?php foreach (User::getAllusers() as $user) : ?>
    <div class="group">
        <p><?= $user->username()?>
            <?= $user->id() === Authentication::User()->id() ? "<strong> (you) </strong>" : "" ?>
        </p>
        <button class="ml-auto">edit button</button>
    </div>
<?php endforeach; ?>

