<h5>Create New Group</h5>

<form method="post" action="<?= $_SERVER["PHP_SELF"] ?>?tab=<?= $page ?>">
    <div class="form-row my-3">
        <label for="group_name" class="col-form-label col-md-3">Group Name:</label>
        <div class="col-md-9">
            <input type="text" id="group_name" class="form-control" name="group_name" placeholder="Enter a group name">
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" name="createGroup">Create Group</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Team</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form action="<?= $_SERVER["PHP_SELF"] ?>" method="post">
                <div class="modal-body">
                        <div class="form-group">
                            <label for="team-name">New Team Name</label>
                            <input type="text" id="team-name" name="team-name" class="form-control">
                            <input type="hidden" id="team-id" name="team-id">
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="group-change" class="btn btn-primary">Save changes</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</form>

<h5>Current Groups</h5>

<?php foreach (Group::allgroups() as $group) : ?>
    <div class="group">
        <p><?= $group->group_name ?></p>
        <form class="ml-auto" action="<?php $_SERVER["PHP_SELF"] ?>" method="post">
            <input type="hidden" name="groupID" value="<?= $group->id ?>">
            <button class="btn btn-danger btn-sm" name="deleteGroup">Delete</button>
            <button type="button" class="btn btn-primary btn-sm edit-button" data-toggle="modal" data-target="#exampleModal" data-teamName="<?= $group->group_name ?>" data-teamId="<?= $group->id ?>">Edit</button>
        </form>
    </div>
<?php endforeach; ?>

<script>
    let editButtons = document.getElementsByClassName("edit-button");

    for (let button of editButtons) {
        button.addEventListener("click", function() {
           let teamName = this.getAttribute("data-teamName");
           let teamId = this.getAttribute("data-teamId");
           console.log(teamName + " " + teamId);

           document.getElementById("team-name").value = teamName;
           document.getElementById("team-name").placeholder = teamName;
           document.getElementById("team-id").value = teamId;
        });
    }


</script>