<h5>Create new user</h5>
<form action="<?= $_SERVER["PHP_SELF"] ?>?tab=<?= $page ?>" method="post">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
    </div>
    <div class="form-group">
        <label for="confirm_password">Confirm Password:</label>
        <input type="password" id="confirm_password" class="form-control" name="confirm_password" placeholder="Confirm password">
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" name="addUser">Create User</button>
    </div>
</form>
<!-- on submit insert role value into user through the db -->

<h5>Current Users</h5>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Username</th>
        <th scope="col">Roles</th>
        <th scope="col">Groups</th>
        <th scope="col">Manage</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach (User::getAllusers() as $index => $user) : ?>
        <tr>
            <th scope="row"><?= $index+1?></th>
            <td><?= $user->username() ?></td>
            <td>
                <?php foreach ($user->roles()->list() as $role) : ?>
                    <span><?= $role ?>, </span>
                <?php endforeach; ?>
            </td>
            <td>
                <?php foreach ($user->teams() as $team) : ?>
                    <span><?= $team ?>, </span>
                <?php endforeach; ?>
            </td>
            <td>
                <button class="ml-auto">edit button</button>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

