<h5>Create New Group</h5>

<form method="post" action="<?= $_SERVER["PHP_SELF"] ?>?tab=<?= $page ?>">
    <div class="form-row my-3">
        <label for="group_name" class="col-form-label col-md-3">Group Name:</label>
        <div class="col-md-9">
            <input type="text" id="group_name" class="form-control" name="group_name" placeholder="Enter a group name">
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" name="createGroup">Create Group</button>
    </div>
</form>

<h5>Current Groups</h5>

<?php foreach (Group::allgroups() as $group) : ?>
    <div class="group">
        <p><?= $group->group_name ?></p>
        <form class="ml-auto" action="<?php $_SERVER["PHP_SELF"] ?>" method="post">
            <input type="hidden" name="groupID" value="<?= $group->id ?>">
            <button class="btn btn-danger btn-sm" name="deleteGroup">Delete</button>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Edit
            </button>
        </form>
    </div>
<?php endforeach; ?>

