<?php require_once "header.phtml"?>

<div class="row justify-content-center align-items-center ">
    <h5>Create new Team</h5>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center ">
        <div class="col-md-6">
            <form>
                <div class="form-group row">
                    <label for="TeamName">TeamName:</label>
                    <input type="text" id="TeamNAme" class="form-control" name="TeamName" placeholder="Please enter the team name">
                </div>
                <div class="form-group row">
                    <button class="btn btn-success" type="submit" name="submit">Create Team</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="row justify-content-center align-items-center ">
    <h5>Set Team Role</h5>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center ">



        <select>
            <?php
            $teams = User::getAllusers();
            ?>

            <?php foreach($teams as $teams) : ?>
                <option value="<?= $teams->teamname() ?>"><?= $teams->teamname() ?></option>
            <?php endforeach; ?>
        </select>

        <select>
            <?php
            $role = Role::allRoles();
            ?>

            <?php foreach ($role as $roles) : ?>
                <option value="<?= $roles->role_name() ?>"><?= $roles->role_name() ?></option>
            <?php endforeach; ?>
        </select>

        <input type="submit">

        <!-- on submit insert role value into user through the db -->
    </div>

    <?php require_once "footer.phtml"?>
