<?php require_once "header.phtml"?>

    <div class="row justify-content-center align-items-center ">
      <h5>Create new user</h5>
    </div>

<div class="container">
    <div class="row justify-content-center align-items-center ">
        <div class="col-md-6">
            <form>
                <div class="form-group row">
                    <label for="username">Username:</label>
                    <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
                </div>

                <div class="form-group row">
                    <label for="password">Password:</label>
                    <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                <div class="form-group row">
                    <button class="btn btn-success" type="submit" name="submit">Create User</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="row justify-content-center align-items-center ">
    <h5>Set user role</h5>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center ">


        <select>
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="opel">Opel</option>
            <option value="audi">Audi</option>
        </select>

        <select>
            <option value="Role 1">Role 1</option>
            <option value="Role 2">Role 2</option>
            <option value="Role 3">Role 3</option>
            <option value="Role 4">Role 4</option>
        </select>

        <input type="submit">

        <!-- on submit insert role value into user through the db -->
    </div>

</div>

<?php require_once "footer.phtml"?>
