<?php require_once "header.phtml"?>

<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6">
            <form>
                <div class="form-group row">
                    <label for="username">Username:</label>
                    <input type="text" id="username" class="form-control" name="username" placeholder="Please enter your user name">
                </div>

                <div class="form-group row">
                    <label for="password">Password:</label>
                    <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                <div class="form-group row">
                    <button class="btn btn-success" type="submit" name="submit">Create User</button>
                </div>
            </form>
        </div>
    </div>
</div>


<?php require_once "footer.phtml"?>
